
name: Auto Sync with Replit
on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9 AM UTC daily
  workflow_dispatch:      # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run sync script
        run: |
          chmod +x ./git-sync.sh
          ./git-sync.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
